hydra:
  run:
    dir: results/${model}_${dataset}_${now:%Y_%m_%d_%H_%M_%S}

# Name of a model.
model: "sensordbscan"

# Name of a dataset.
dataset: "reinartz_tep"

# Size of a sliding window to generate a sequence of samples.
window_size: 100

# Size of a step for sliding window to generate a sequence of samples.
step_size: 5

# Random seed of a training process makes results reproducable.
random_seed: 0

# Batch size in evaluation
eval_batch_size: 4096

# Path to a .pth file with pretrained model.
path_to_model:

pretraining:
  dataset_name: ${dataset}
  dataset_window_size: 300
  step_size: 1
  train_batch_size: 1280
  visualize_batch_size: 256
  num_features: 30

  augmentor:
    mean_mask_length: 6
    masking_ratio: 0.5

    weak_jitter_sigma: 0.08
    weak_scaling_loc: 1.8
    weak_scaling_sigma: 0.1
    strong_scaling_loc: 0.5
    strong_scaling_sigma: 0.1
    strong_permute_max_segments: 17

  model_input_length: 100
  model_dim: 128
  ff_dim: 512
  num_heads: 16
  num_layers: 3
  dropout_rate: 0.1
  norm: 'LayerNorm'

  lr: 1e-3
  weight_decay: 1e-5
  contrastive_weight: 0.7
  epochs: 7

  device: 'cuda'

epochs: 25
clustering_finetuning_epochs: 3

encoder_dim: 64
encoder_lr: 1e-5

device: 'cuda'
batch_size: 1024
metric: 'euclidean'
epsilon: 1
min_samples: 1000
max_triplets: 102400
n_samples_to_select: 1000
ch_score_momentum: 0.9
max_mbytes_per_batch: 4096
dbscan_epsilon_multiplier: 0.95

handle_outliers: True
knn_neighbors: 50

classes: 'all'
